server:
  address: 0.0.0.0
  port: 8989

spring:
  neo4j:
    uri: bolt://192.168.2.128:7687
    authentication:
      username: neo4j
      password: 520824zxk
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev
  ai:
#    websearch:
#      api-key:  ${websearch.api-key}
#      searxng:
#        url: "http://127.0.0.1:8080/search"
#        nums: 10
#        engines: "duckduckgo,google,bing,brave,mojeek,presearch,qwant,startpage,yahoo,arxiv,crossref,google_scholar,internetarchivescholar,semantic_scholar"
    openai:
      api-key: sk-d9e4ff14ddc1428ea34311e3423ee000
    dashscope:
      api-key: sk-d9e4ff14ddc1428ea34311e3423ee000
      embedding:
        options:
          model: text-embedding-v3
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: sdh-rag-index
        dimensions: 1536
        similarity: cosine
  elasticsearch:
    uris: 192.168.2.128:9200
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sdh_rag?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  data:
    redis:
      port: 6379              # Redis 服务器端口，默认为 6379
#      password:               # Redis 密码，默认为空
      timeout: 5000ms         # 连接超时时间
      lettuce:
        pool:
          max-active: 8       # 最大连接数
          max-idle: 4         # 最大空闲连接数
          min-idle: 1         # 最小空闲连接数
          max-wait: 2000ms



xushu:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: xushu_jwt_secret_key_for_admin_access_256_bits_required
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: xushu_jwt_secret_key_for_user_access_256_bits_required
    user-ttl: 7200000
    user-token-name: token

# MinIO 配置
minio:
  endpoint: http://192.168.2.128:9000
  access-key: admin
  secret-key: password
  bucket-name: sdh-documents



logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug

knowledge:
  default:
    chunk-size: 500
    chunk-overlap: 50
    embeddingModel: text-embedding-v3
    rankModel: qwen3-rerank